# version: '3.8'

services:
  rllm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_NAME: rllm
        PYTHON_VERSION: 3.11
    volumes:
      - .:/workspace/rllm/  # Mount current directory to /workspace/open-r1/
      - ~/.cache/huggingface/:/root/.cache/huggingface/
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    command: tail -f /dev/null
    restart: unless-stopped
    shm_size: '16gb'
    ulimits:
      memlock: -1
      stack: 67108864
